version: "3.4"
services:
  elasticsearch_test:
    image: "elasticsearch:8.11.3"
    environment:
      - bootstrap.memory_lock=${ES_MEMORY_LOCK:-false}
      - "ES_JAVA_OPTS=-Xms${TEST_ES_HEAP_SIZE:-500m} -Xmx${TEST_ES_HEAP_SIZE:-500m}"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
    ports:
      - "127.0.0.1:9250:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
