name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [
      synchronize, # PR was updated
      opened, # PR was open
      reopened # PR was reopened
    ]

jobs:
  ruby-3:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2' ]
        gemfile: [rails.6.1.activerecord, rails.7.0.activerecord, rails.7.1.activerecord]
    name: ${{ matrix.ruby }}-${{ matrix.gemfile }}

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    services:
      redis:
        # Docker Hub image
        image: redis
        ports:
          - '6379:6379'
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Start containers
        run: |
          docker compose up elasticsearch_test -d
          sleep 15

      - name: Tests
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: bundle exec rubocop --format simple
